// Mocks generated by Mockito 5.0.16 from annotations
// in grocery_store_app/test/presentation/cubit_app_presenter_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:grocery_store_app/domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [LoadProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadProducts extends _i1.Mock implements _i2.LoadProducts {
  MockLoadProducts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.ProductEntity>> load() =>
      (super.noSuchMethod(Invocation.method(#load, []),
              returnValue:
                  Future<List<_i2.ProductEntity>>.value(<_i2.ProductEntity>[]))
          as _i3.Future<List<_i2.ProductEntity>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LoadUserAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadUserAccount extends _i1.Mock implements _i2.LoadUserAccount {
  MockLoadUserAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.UserEntity?> load() =>
      (super.noSuchMethod(Invocation.method(#load, []),
              returnValue: Future<_i2.UserEntity?>.value())
          as _i3.Future<_i2.UserEntity?>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LoadUserCart].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadUserCart extends _i1.Mock implements _i2.LoadUserCart {
  MockLoadUserCart() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.CartEntity?> load(String? userId) =>
      (super.noSuchMethod(Invocation.method(#load, [userId]),
              returnValue: Future<_i2.CartEntity?>.value())
          as _i3.Future<_i2.CartEntity?>);
  @override
  String toString() => super.toString();
}
